/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import controller.AssistidosController;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Assistidos;
import util.ConexaoPostGree;

/**
 *
 * @author ASGS
 */
public class AssistidoSearchView extends javax.swing.JFrame {

    /**
     * Creates new form AssistisoPrincipalView
     */
    public AssistidoSearchView() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAssistido = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jcB = new javax.swing.JComboBox<>();
        jBSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCOpcoes = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jBConsultar = new javax.swing.JButton();
        jBInserir = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        JBcolabora1 = new javax.swing.JButton();
        JtbAddAss = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setViewportView(jTAssistido);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jcB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jcB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Cpf", "Identidade", "Ativo" }));
        jcB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBActionPerformed(evt);
            }
        });

        jBSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/Multiply_25px.png"))); // NOI18N
        jBSair.setContentAreaFilled(false);
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 200));

        jCOpcoes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCOpcoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jCOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jBConsultar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jBConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/Search_32px.png"))); // NOI18N
        jBConsultar.setText("Consultar");
        jBConsultar.setContentAreaFilled(false);
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });

        jBInserir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jBInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/File_32px.png"))); // NOI18N
        jBInserir.setText("Inserir");
        jBInserir.setContentAreaFilled(false);
        jBInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInserirActionPerformed(evt);
            }
        });

        jBAlterar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jBAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/Edit_32px.png"))); // NOI18N
        jBAlterar.setText("Alterar");
        jBAlterar.setContentAreaFilled(false);
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        JBcolabora1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JBcolabora1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/People_32px.png"))); // NOI18N
        JBcolabora1.setText("Assistidos");
        JBcolabora1.setContentAreaFilled(false);
        JBcolabora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcolabora1ActionPerformed(evt);
            }
        });

        JtbAddAss.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JtbAddAss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/Plus Math_32px.png"))); // NOI18N
        JtbAddAss.setText("Adicionar a Projeto");
        JtbAddAss.setContentAreaFilled(false);
        JtbAddAss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtbAddAssActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/Test Passed_32px.png"))); // NOI18N
        jButton1.setText("Lista de Presença");
        jButton1.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBcolabora1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JtbAddAss)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConsultar)
                    .addComponent(jBInserir)
                    .addComponent(jBAlterar)
                    .addComponent(JBcolabora1)
                    .addComponent(JtbAddAss)
                    .addComponent(jButton1)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jcB, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                        .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jcB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcBActionPerformed

    private void jBInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInserirActionPerformed
        AssistidoEditView v = new AssistidoEditView();
        v.setLocationRelativeTo(null);
        v.logo(true);
        v.setVisible(true);

        jBConsultar.doClick();
    }//GEN-LAST:event_jBInserirActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        int linha = jTAssistido.getSelectedRow();

        //Verifica se existe alguem selecionado 
        if (linha >= 0) {
            Long id = (Long) jTAssistido.getValueAt(linha, 0);

            Assistidos Assistido = AssistidosController.getInstance().buscarID(id);

            AssistidoEditView v = new AssistidoEditView();
            v.setLocationRelativeTo(null);
            v.setDados(Assistido);
            v.logo(false);
            v.setVisible(true);

            jBConsultar.doClick();
    }//GEN-LAST:event_jBAlterarActionPerformed
else {
            JOptionPane.showMessageDialog(this, "Nenhum Registro foi selecionado.. seu burro.");
        }

    }
    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        dispose();
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed

        List<Assistidos> c = AssistidosController.getInstance().
                busca(jcB.getSelectedIndex(),
                        jCOpcoes.getText());

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Nome");
        modelo.addColumn("RG");
        modelo.addColumn("Telefone");
        modelo.addColumn("Profissão");
        modelo.addColumn("Cpf");
        modelo.addColumn("Renda");
        modelo.addColumn("Idade");
        modelo.addColumn("Rua");
        modelo.addColumn("Numero");
        modelo.addColumn("Complemento");
        modelo.addColumn("Bairro");
        modelo.addColumn("Cidade");
        modelo.addColumn("Estado");
        modelo.addColumn("Ativo");

        for (Assistidos i : c) {
            // Seta os valores do objeto para o JTableModel 
            modelo.addRow(new Object[]{i.getId(), i.getNome(), i.getIdentidade(), i.getTelefone(), i.getProfissao(), i.getCPF(), i.getRenda(), i.getIdade(), i.getRua(), i.getNumero(), i.getComplemento(), i.getBairro(), i.getCidade(), i.getEstado(), i.getAtivo()});
        }
        //Limpa a JTable (Grid)
        jTAssistido.removeAll();
        //Seta o modelo para a Grid 
        jTAssistido.setModel(modelo);

        //Ajusta o tamanho da primeira coluna 
        jTAssistido.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTAssistido.getColumnModel().getColumn(0).setPreferredWidth(360);
        jTAssistido.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTAssistido.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTAssistido.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTAssistido.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTAssistido.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTAssistido.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTAssistido.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTAssistido.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTAssistido.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTAssistido.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTAssistido.getColumnModel().getColumn(0).setPreferredWidth(60);
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jCOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCOpcoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCOpcoesActionPerformed

    private void JBcolabora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcolabora1ActionPerformed
        int linha = jTAssistido.getSelectedRow();

        //Verifica se existe alguem selecionado
        if (linha >= 0) {
            Long id = (Long) jTAssistido.getValueAt(linha, 0);

            Assistidos c = AssistidosController.getInstance().buscarID(id);

            AmparatosPView v = new AmparatosPView();

            v.setLocationRelativeTo(null);
            v.Colaboraçao(c);
            v.setVisible(true);

            jBConsultar.doClick();

        } else {
            JOptionPane.showMessageDialog(this, "Nenhum Registro foi selecionado.");
        }
    }//GEN-LAST:event_JBcolabora1ActionPerformed

    private void JtbAddAssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtbAddAssActionPerformed
       int linha = jTAssistido.getSelectedRow();

       
        if (linha >= 0) {
            Long id = (Long) jTAssistido.getValueAt(linha, 0);

            Assistidos c = AssistidosController.getInstance().buscarID(id);

            AddProjetoView v = new AddProjetoView();

            v.setLocationRelativeTo(null);
            v.setDados(c);
            v.LoadDoa();
            v.setVisible(true);
               
            jBConsultar.doClick();

        } 
    }//GEN-LAST:event_JtbAddAssActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssistidoSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssistidoSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssistidoSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssistidoSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssistidoSearchView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBcolabora1;
    private javax.swing.JToggleButton JtbAddAss;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBInserir;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCOpcoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTAssistido;
    private javax.swing.JComboBox<String> jcB;
    // End of variables declaration//GEN-END:variables
}
