/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.LoginController;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Login;


public class LoginSearchView extends javax.swing.JFrame {

    /**
     * Creates new form AtendenteSearchView
     */
    public LoginSearchView() {
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jbGravar2 = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbInserir = new javax.swing.JButton();
        jbOk = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtfOpcoes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAtendente = new javax.swing.JTable();
        jbExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jbGravar2.setBackground(new java.awt.Color(255, 255, 255));
        jbGravar2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbGravar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/Multiply_25px.png"))); // NOI18N
        jbGravar2.setContentAreaFilled(false);
        jbGravar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravar2ActionPerformed(evt);
            }
        });

        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/Edit_32px.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setToolTipText("Clique aqui para Alterar");
        jbAlterar.setContentAreaFilled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/File_32px.png"))); // NOI18N
        jbInserir.setText("Inserir");
        jbInserir.setToolTipText("Clique aqui para Inserir");
        jbInserir.setContentAreaFilled(false);
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/Search_32px.png"))); // NOI18N
        jbOk.setText("Consultar Usuario");
        jbOk.setContentAreaFilled(false);
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 200));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jtfOpcoes.setToolTipText("Digite aqui o valor para pesquisar");
        jtfOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfOpcoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtAtendente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtAtendente);

        jbExcluir.setBackground(new java.awt.Color(255, 255, 255));
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/Cancel_32px.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setContentAreaFilled(false);
        jbExcluir.setOpaque(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jbOk, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluir)
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbGravar2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jbGravar2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar)
                    .addComponent(jbInserir)
                    .addComponent(jbOk)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed

        List<Login> l = LoginController.getInstance().
        buscar(jtfOpcoes.getText());
        // Cria um defaultTableModel para ser usado na JTable com os campos que serão exibidos na tela
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Código (ID)");
        modelo.addColumn("Usuario");
        modelo.addColumn("Senha");
        modelo.addColumn("Administrador");

        for (Login i : l) {
            // Seta os valores do objeto para o JTableModel
            modelo.addRow(new Object[]{i.getId(), i.getUsuario(), i.getSenha(), i.getAdm()});
        }
        //Limpa a JTable (Grid)
        jtAtendente.removeAll();
        //Seta o modelo para a Grid
        jtAtendente.setModel(modelo);

        //Ajusta o tamanho da primeira coluna
        jtAtendente.getColumnModel().getColumn(0).setPreferredWidth(60);
        jtAtendente.getColumnModel().getColumn(1).setPreferredWidth(60);

        //Ocutar coluna ID
        ///jtAluno.getColumnModel().getColumn(0).setMinWidth(0);
        //jtAluno.getColumnModel().getColumn(0).setMaxWidth(0);
        //jtAluno.getColumnModel().getColumn(0).setWidth(0);
    }//GEN-LAST:event_jbOkActionPerformed

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        LoginInsetView v = new LoginInsetView();
        v.setLocationRelativeTo(null);

        v.setVisible(true);

        jbOk.doClick();
    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        int linha = jtAtendente.getSelectedRow();

        //Verifica se existe alguem selecionado
        if (linha >= 0) {
            Long id = (Long) jtAtendente.getValueAt(linha, 0);

            Login c = LoginController.getInstance().buscarID(id);

            LoginEditView2 v = new LoginEditView2();

            v.setLocationRelativeTo(null);
            v.setDados(c);
            v.setVisible(true);

            jbOk.doClick();

        } else {
            JOptionPane.showMessageDialog(this, "Nenhum Registro foi selecionado.");
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jtfOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfOpcoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfOpcoesActionPerformed

    private void jbGravar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGravar2ActionPerformed
        dispose();
    }//GEN-LAST:event_jbGravar2ActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
            int linha = jtAtendente.getSelectedRow();

        //Verifica se existe alguem selecionado
        if (linha >= 0) {

            if (JOptionPane.showConfirmDialog(this, "Deseja deletar, seu cavalo?",
                    "Opção", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                // Pega o valor da primeira coluna o ID do aluno
                Long id = (Long) jtAtendente.getValueAt(linha, 0);

                //Dispar o metodo de deleçao do a partir do ID do aluno passado
                if (LoginController.getInstance().deletar(id)) {
                    JOptionPane.showMessageDialog(this, "Registro deletado com sucesso.");

                    //jbOkActionPerformed(evt); ou
                    jbOk.doClick();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro na deleção do Registro.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum registro selecionado.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jbExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSearchView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbGravar2;
    private javax.swing.JButton jbInserir;
    private javax.swing.JButton jbOk;
    private javax.swing.JTable jtAtendente;
    private javax.swing.JTextField jtfOpcoes;
    // End of variables declaration//GEN-END:variables
}
