/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DoadorController;
import controller.VoluntarioController;
import java.awt.Color;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Doador;
import model.Voluntario;


public class VoluntarioSearchView extends javax.swing.JFrame {

   
    public VoluntarioSearchView() {
     
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbInserir = new javax.swing.JButton();
        jbOk = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jcbOpcoes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAtendente = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jtfOpcoes = new javax.swing.JTextField();
        jbGravar2 = new javax.swing.JButton();
        JBcolabora = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jbInserir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/File_32px.png"))); // NOI18N
        jbInserir.setText("Inserir");
        jbInserir.setToolTipText("Clique aqui para Inserir");
        jbInserir.setContentAreaFilled(false);
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbOk.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/Search_32px.png"))); // NOI18N
        jbOk.setText("Consultar");
        jbOk.setContentAreaFilled(false);
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        jbAlterar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/Edit_32px.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setToolTipText("Clique aqui para Alterar");
        jbAlterar.setContentAreaFilled(false);
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jcbOpcoes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jcbOpcoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "CPF", "Identidade", "Ativo" }));
        jcbOpcoes.setOpaque(false);
        jcbOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOpcoesActionPerformed(evt);
            }
        });

        jtAtendente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtAtendente);

        jPanel2.setBackground(new java.awt.Color(0, 0, 200));

        jtfOpcoes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jtfOpcoes.setToolTipText("Digite aqui o valor para pesquisar");
        jtfOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfOpcoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jtfOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtfOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jbGravar2.setBackground(new java.awt.Color(255, 255, 255));
        jbGravar2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbGravar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/Multiply_25px.png"))); // NOI18N
        jbGravar2.setContentAreaFilled(false);
        jbGravar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGravar2ActionPerformed(evt);
            }
        });

        JBcolabora.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        JBcolabora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/Account_32px.png"))); // NOI18N
        JBcolabora.setText("Colaboração");
        JBcolabora.setContentAreaFilled(false);
        JBcolabora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcolaboraActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ImgNovo/Plus Math_32px.png"))); // NOI18N
        jButton2.setText("Adcionar a Projeto");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1346, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jcbOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbOk, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBcolabora)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbGravar2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbGravar2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcbOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbInserir)
                                .addComponent(jbAlterar)
                                .addComponent(JBcolabora)
                                .addComponent(jButton2))
                            .addComponent(jbOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        VoluntarioInsetView v = new VoluntarioInsetView();
        v.setLocationRelativeTo(null);
        v.logo(true);
        v.LoadDoa();

        v.setVisible(true);

        jbOk.doClick();
    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed

        List<Voluntario> c = VoluntarioController.getInstance().
                busca(jcbOpcoes.getSelectedIndex(), 
                       jtfOpcoes.getText());        
        // Cria um defaultTableModel para ser usado na JTable com os campos que serão exibidos na tela
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Nome");
        modelo.addColumn("RG");
        modelo.addColumn("Telefone");
        modelo.addColumn("Profissão");
        modelo.addColumn("CPF");
        modelo.addColumn("Rua");
        modelo.addColumn("Numero");
        modelo.addColumn("Complemento");
        modelo.addColumn("Bairro");
        modelo.addColumn("Cidade");
        modelo.addColumn("Estado");
        modelo.addColumn("Dia Atuação");
        modelo.addColumn("Horas de Atuação");
        modelo.addColumn("Ativo");
        modelo.addColumn("Login");



        for (Voluntario i : c) {
            // Seta os valores do objeto para o JTableModel
            modelo.addRow(new Object[]{i.getId(), i.getNome(), i.getIdentidade(), i.getTelefone(), i.getProfissao(), i.getCPF(), i.getRua(), i.getNumero(), 
                i.getComplemento(), i.getBairro(), i.getCidade(), i.getEstado(), i.getDia_atuacao(), i.getHora(), i.getAtivo(), i.getLog().getUsuario()});
        }
        //Limpa a JTable (Grid)
        jtAtendente.removeAll();
        //Seta o modelo para a Grid
        jtAtendente.setModel(modelo);

        //Ajusta o tamanho da primeira coluna
        jtAtendente.getColumnModel().getColumn(0).setPreferredWidth(5);
        jtAtendente.getColumnModel().getColumn(1).setPreferredWidth(200);
        jtAtendente.getColumnModel().getColumn(2).setPreferredWidth(20);
        jtAtendente.getColumnModel().getColumn(3).setPreferredWidth(20);
        jtAtendente.getColumnModel().getColumn(4).setPreferredWidth(50);
        jtAtendente.getColumnModel().getColumn(5).setPreferredWidth(50);
        jtAtendente.getColumnModel().getColumn(6).setPreferredWidth(50);
        jtAtendente.getColumnModel().getColumn(7).setPreferredWidth(1);
        jtAtendente.getColumnModel().getColumn(8).setPreferredWidth(1);
        jtAtendente.getColumnModel().getColumn(9).setPreferredWidth(20);
        jtAtendente.getColumnModel().getColumn(10).setPreferredWidth(30);
        jtAtendente.getColumnModel().getColumn(11).setPreferredWidth(1);
        jtAtendente.getColumnModel().getColumn(12).setPreferredWidth(1);
        jtAtendente.getColumnModel().getColumn(13).setPreferredWidth(1);
        jtAtendente.getColumnModel().getColumn(14).setPreferredWidth(1);
        
    }//GEN-LAST:event_jbOkActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        int linha = jtAtendente.getSelectedRow();

        //Verifica se existe alguem selecionado
        if (linha >= 0) {
            Long id = (Long) jtAtendente.getValueAt(linha, 0);

            Voluntario c = VoluntarioController.getInstance().buscarID(id);

            VoluntarioInsetView v = new VoluntarioInsetView();

            v.setLocationRelativeTo(null);
            v.LoadDoa();
            v.setDados(c);
            v.logo(false);
            v.setVisible(true);
               
            jbOk.doClick();

        } else {
            JOptionPane.showMessageDialog(this, "Nenhum Registro foi selecionado.");
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jtfOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfOpcoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfOpcoesActionPerformed

    private void jcbOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOpcoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbOpcoesActionPerformed

    private void jbGravar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGravar2ActionPerformed
        dispose();
    }//GEN-LAST:event_jbGravar2ActionPerformed

    private void JBcolaboraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcolaboraActionPerformed
        int linha = jtAtendente.getSelectedRow();

        //Verifica se existe alguem selecionado
        if (linha >= 0) {
            Long id = (Long) jtAtendente.getValueAt(linha, 0);

            Voluntario c = VoluntarioController.getInstance().buscarID(id);

            ColaboradorView v = new ColaboradorView();

            v.setLocationRelativeTo(null);
            v.Colaboraçao(c);
            v.setVisible(true);
               
            jbOk.doClick();

        } else {
            JOptionPane.showMessageDialog(this, "Nenhum Registro foi selecionado.");
        }


    }//GEN-LAST:event_JBcolaboraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           int linha = jtAtendente.getSelectedRow();

       
        if (linha >= 0) {
            Long id = (Long) jtAtendente.getValueAt(linha, 0);

            Voluntario c = VoluntarioController.getInstance().buscarID(id);

            ColaboracaoView v = new ColaboracaoView();

            v.setLocationRelativeTo(null);
            v.setDados(c);
            v.LoadDoa();
            v.setVisible(true);
               
            jbOk.doClick();

        } else {
            JOptionPane.showMessageDialog(this, "Nenhum Registro foi selecionado.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoluntarioSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoluntarioSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoluntarioSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoluntarioSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoluntarioSearchView().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBcolabora;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbGravar2;
    private javax.swing.JButton jbInserir;
    private javax.swing.JButton jbOk;
    private javax.swing.JComboBox<String> jcbOpcoes;
    private javax.swing.JTable jtAtendente;
    private javax.swing.JTextField jtfOpcoes;
    // End of variables declaration//GEN-END:variables

   
}
